### ISSUE TITLE
Cooking recipes not showing

### ISSUE THREAD

**Issue by PerfectlyInSane** [firefoxpdm/Rainbeau-s-Fishing#2]
None of the cooking recipes are showing in the "Electric stove". The recipes do appear and are usable in the "Fueled stove".

Other users have reported the same issue in the comments of the Steam release page. (Though I understand that is someone else publishing this release.)
(https://steamcommunity.com/sharedfiles/filedetails/?id=2034028432)

**Comment by firefoxpdm** [comment]
I can see all the simple recipies, when only this mod is loaded, both for the electric and the fueled stoves:

![image](https://user-images.githubusercontent.com/2911221/79022362-09e01e80-7b7e-11ea-938d-e3a31d8f142e.png)
![image](https://user-images.githubusercontent.com/2911221/79022369-0e0c3c00-7b7e-11ea-9ca0-c0c5bd9f1f36.png)

Are you, by any chance, using the Vanilla Furniture Expanded - Production mod as well? Because when I add that one (either before or after the fishing mod), the electric stove loses the extra recipes.

**Comment by firefoxpdm** [comment]
Some additional info to this problem:
There is an option in the mod whether to add the seafood recipies or not. Because of this, the recipies are not assigned to the electric stove in the xml. Instead they are assigned to them programatically, when the app loads.
This would be working fine, but then (in my case) the VFE mod comes and fetches all the recipes from the electric stove, because it wants to copy all of them to its own large stove. I haven't verified this yet, but my gut feeling is that as soon as that happens, some internal mechanism of the game kicks in that eagerly calculates all available recipes for the electric stove, and from that point on the additional recipes from Fishing are ignored.

This particular issue could be completely circumvented if the new cooking recipes were assigned to the stoves in the xml. But that would mean that the "Use Seafood Recipes" option would have to be removed. Because as far as I know there is no way to consider mod settings in the XMLs themselves.

**Comment by PerfectlyInSane** [comment]
I am using VFE. Is there any need to have the option to turn of the seafood recipes?
It doesn't make the meat unusable in other recipes so if anyone doesn't want to use them, they wouldn't have to.

**Comment by firefoxpdm** [comment]
The rationale from RF was that it might make the list of available bills too long. There is also the question of the bulk recipes that are added when one of two other mods are detected.
I will try and check if I can somehow add the new recipies directly to the electric and fueled stove programatically - although this solution would require Fishing to be loaded before VFE. If I cannot figure that out, then for the sake of compatibility I am going to remove the configuration option and do the recipe handling in the xml.

**Comment by firefoxpdm** [comment]
I have a fix without having to remove the configuration option:

![image](https://user-images.githubusercontent.com/2911221/79038503-01b5cc80-7bda-11ea-9302-1b48b44eb68b.png)

Release will come soon-ish.

**Comment by firefoxpdm** [comment]
Github release done.

The seafood recipes option remains for now, unless some other compatibility issue pops up.
For the large stove to inherit the recipes, the fishing mod must be loaded before the VFE one. I have added the necessary load order information to the About.xml so the mod sorter can automatically manage this.

**Comment by PerfectlyInSane** [comment]
Appreciate you looking at this and finding a solution. Cheers.
